// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddKeyPair(arg1:main.AddKeyPairInput):Promise<main.AddKeyPairResult>;

export function AddSecret(arg1:main.AddSecretInput):Promise<main.IDResult>;

export function ArchiveSecret(arg1:string,arg2:boolean):Promise<main.BoolResult>;

export function DeleteSecret(arg1:string):Promise<main.BoolResult>;

export function ExportBackup(arg1:string):Promise<Array<number>>;

export function GetAuditLog(arg1:number):Promise<Array<main.AuditDTO>>;

export function GetCurrentTime():Promise<number>;

export function GetCustomFields(arg1:string):Promise<string>;

export function GetHealth():Promise<Array<main.HealthDTO>>;

export function GetSetting(arg1:string):Promise<string>;

export function GetVaultPath():Promise<string>;

export function GetVersion():Promise<string>;

export function ImportBackup(arg1:Array<number>,arg2:string):Promise<main.BoolResult>;

export function ImportCommit(arg1:string,arg2:main.ColMapDTO):Promise<main.ImportCommitResult>;

export function ImportPreview(arg1:string,arg2:main.ColMapDTO):Promise<main.ImportPreviewResult>;

export function InitVault(arg1:string):Promise<main.BoolResult>;

export function IsInitialized():Promise<boolean>;

export function IsUnlocked():Promise<boolean>;

export function ListProviders():Promise<Array<main.ProviderDTO>>;

export function ListSecrets(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<Array<main.SecretSummaryDTO>>;

export function Lock():Promise<void>;

export function RevealSecret(arg1:string):Promise<string>;

export function SetCustomFields(arg1:string,arg2:string):Promise<main.BoolResult>;

export function SetSetting(arg1:string,arg2:string):Promise<main.BoolResult>;

export function TagSecret(arg1:string,arg2:string):Promise<main.BoolResult>;

export function Unlock(arg1:string):Promise<main.BoolResult>;

export function UpdateSecretValue(arg1:string,arg2:string):Promise<main.BoolResult>;

export function VerifyAuditChain():Promise<number>;
