// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddKeyPair(arg1) {
  return window['go']['main']['App']['AddKeyPair'](arg1);
}

export function AddSecret(arg1) {
  return window['go']['main']['App']['AddSecret'](arg1);
}

export function ArchiveSecret(arg1, arg2) {
  return window['go']['main']['App']['ArchiveSecret'](arg1, arg2);
}

export function DeleteSecret(arg1) {
  return window['go']['main']['App']['DeleteSecret'](arg1);
}

export function ExportBackup(arg1) {
  return window['go']['main']['App']['ExportBackup'](arg1);
}

export function GetAuditLog(arg1) {
  return window['go']['main']['App']['GetAuditLog'](arg1);
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetCustomFields(arg1) {
  return window['go']['main']['App']['GetCustomFields'](arg1);
}

export function GetHealth() {
  return window['go']['main']['App']['GetHealth']();
}

export function GetSetting(arg1) {
  return window['go']['main']['App']['GetSetting'](arg1);
}

export function GetVaultPath() {
  return window['go']['main']['App']['GetVaultPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function ImportBackup(arg1, arg2) {
  return window['go']['main']['App']['ImportBackup'](arg1, arg2);
}

export function ImportCommit(arg1, arg2) {
  return window['go']['main']['App']['ImportCommit'](arg1, arg2);
}

export function ImportPreview(arg1, arg2) {
  return window['go']['main']['App']['ImportPreview'](arg1, arg2);
}

export function InitVault(arg1) {
  return window['go']['main']['App']['InitVault'](arg1);
}

export function IsInitialized() {
  return window['go']['main']['App']['IsInitialized']();
}

export function IsUnlocked() {
  return window['go']['main']['App']['IsUnlocked']();
}

export function ListProviders() {
  return window['go']['main']['App']['ListProviders']();
}

export function ListSecrets(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ListSecrets'](arg1, arg2, arg3, arg4);
}

export function Lock() {
  return window['go']['main']['App']['Lock']();
}

export function RevealSecret(arg1) {
  return window['go']['main']['App']['RevealSecret'](arg1);
}

export function SetCustomFields(arg1, arg2) {
  return window['go']['main']['App']['SetCustomFields'](arg1, arg2);
}

export function SetSetting(arg1, arg2) {
  return window['go']['main']['App']['SetSetting'](arg1, arg2);
}

export function TagSecret(arg1, arg2) {
  return window['go']['main']['App']['TagSecret'](arg1, arg2);
}

export function Unlock(arg1) {
  return window['go']['main']['App']['Unlock'](arg1);
}

export function UpdateSecretValue(arg1, arg2) {
  return window['go']['main']['App']['UpdateSecretValue'](arg1, arg2);
}

export function VerifyAuditChain() {
  return window['go']['main']['App']['VerifyAuditChain']();
}
